myapi/urls.py
from django.urls import re_path
from . import views
from rest_framework_simplejwt import views as jwt_views
urlpatterns = [
    # 2 URLs : 1 cái cho đăng nhập (lấy token, gửi username/password lên)
    #   Trả về 2 token: access (dùng để truy cập) và refresh (gia hạn khi access bị expired)
    #   URL dùng lấy access token  mới từ refresh
    re_path(r"^token$",jwt_views.TokenObtainPairView.as_view(), name='get_token'),
    re_path(r"^token/refresh$", jwt_views.TokenRefreshView.as_view(), name='refresh_token'),
    re_path(r"^pets$", views.api_list_pets, name='api_list_pets'),
    re_path(r"^pet/detail/(?P<pet_id>[\w]+)$", views.api_detail_pet, name='api_detail_pet'),
    re_path(r"^pet/add$", views.api_add_pet, name='api_add_pet'),
    re_path(r"^pet/update/(?P<pet_id>[\w]+)$", views.api_update_pet, name='api_update_pet'),
    re_path(r"^pet/delete/(?P<pet_id>[\w]+)$", views.api_delete_pet, name='api_delete_pet'),
]

myapp/urls.py
from django.urls import re_path, path # Django phiên bản nhơ 4.0 là url
# Từ 4.0 đổi thành re_path
# Import view mới viết vào.
# from views import my_view
from django.contrib.auth import views as auth_views
from . import views, class_views, user_views
# from .views import my_view
app_name = 'myapp'
urlpatterns = [
    re_path(r"^$", views.index, name='index'),
    re_path(r"^pet/add$", views.add_pet, name='add_pet'),
    re_path(r"^pet/view/(?P<pet_id>[\w]+)$", views.detail_pet, name="detail_pet"), 
    # path("update/<str:pet_id>", views.update_pet, name='update_pet'),
    re_path(r"^pet/update/(?P<pet_id>[\w]+)$", views.update_pet, name="update_pet"), 
    re_path(r"^pet/delete/(?P<pet_id>[\w]+)$", views.delete_pet, name="delete_pet"), 

    re_path(r"^class$", class_views.PetListView.as_view(), name='class_index'),
    re_path(r"^class/add$", class_views.PetCreateView.as_view(), name='class_add_pet'),
    re_path(r"^class/view/(?P<pk>[\w]+)$", class_views.PetDetailView.as_view(), name='class_detail_pet'),
    re_path(r"^class/update/(?P<pk>[\w]+)$", class_views.PetUpdateView.as_view(), name='class_update_pet'),
    re_path(r"^class/delete/(?P<pk>[\w]+)$", class_views.PetDeleteView.as_view(), name='class_delete_pet'),
    
    re_path(r"^user/register$",user_views.register_user, name='register_user'),
    re_path(r"^user/login$",user_views.login_user, name='login_user'),
    re_path(r"^user/logout$", auth_views.LogoutView.as_view(next_page='/'), name='logout_user'),
    re_path(r"^user/change$", user_views.change_password, name='change_password'),
    re_path(r"^user/validate$", user_views.validate_username, name='validate_username'),
]

myweb/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('', include('myshop.urls')),
    path('admin/', admin.site.urls),
    # path('api/', include('myapi.urls')),
    # path('myapp/', include('myapp.urls'))
]

myapp/models.py
from operator import mod
from pyexpat import model
from django.db import models

# Create your models here.
# Bảng đơn
class Student(models.Model):
    # Tên table liên kết với class model: <tên app viết thường>_<tên class viết thường>
    # name, age, gender, email, phone
    # name, email, phone (lấy chữ 0 ở đầu sdt), gender: TEXT
    # age: INTEGER
    name = models.CharField(max_length=30)
    age = models.IntegerField()
    gender = models.BooleanField() # True: name, False là nữ
    email = models.CharField(max_length=10)
    phone = models.CharField(max_length=10)
    address = models.TextField(default="Hồ Chí Minh") # textfield là không giới hạn về độ dài

    def __str__(self):
        return self.name

# Những lệnh kiểm tra với thay đổi của models.py
# 1. Kiễm tra xem mình có thay đổi gì hay không ? python manage.py makemigrations <tên app>
    # Không có tên app thì sẽ toàn bộ các app

# 2. Xem các thay đổi với dạng SQL command: python manage.py sqlmigrate <tên app> <số tạo ở command trên>

# 3. Apply các thay đổi xuống database: python manage.py migrate

# Quan hệ 1-1
class Place(models.Model):
    name = models.CharField(max_length=50)
    address = models.TextField()

    def __str__(self):
        return f"{self.name} is a Place"

    class Meta:
        db_table = "Place" # `db_table` định tên tùy chọn của table trong DB

class Restaurant(models.Model):
    place = models.OneToOneField(
        Place,
        on_delete=models.CASCADE, # `on_delete: CASCADE` khi mà mình xóa khóa chính của liên kết FK thì sẽ tự đông xóa hết theo FK 
        primary_key=True,
    )
    serves_hot_dogs = models.BooleanField(default=False)
    serves_pizza = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.place.name} the restaurant"

    class Meta:
        db_table = "Restaurant"

class Reporter(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.EmailField()

    def __str__(self):
        return "%s %s" % (self.first_name, self.last_name)

    class Meta:
        db_table = "Reporter"

class Article(models.Model):
    headline = models.CharField(max_length=100)
    pub_date = models.DateField()
    reporter = models.ForeignKey(Reporter, on_delete=models.CASCADE)

    def __str__(self):
        return self.headline

    class Meta:
        ordering = ['headline']
        db_table = "Article"

# class Publication(models.Model):
#     title = models.CharField(max_length=30)

#     class Meta:
#         ordering = ['title'] # Dùng để sắp xếp, tăng dần ['title'] / ['-title'] giảm dần
#         db_table = "Publication"

#     def __str__(self):
#         return self.title

# class Article(models.Model):
    # # Tên table tạo mới thì sẽ lấy <tên class chứa ManyToManyField>_<trường ManyToMany>
    # headline = models.CharField(max_length=100)
    # publications = models.ManyToManyField(Publication)

    # class Meta:
    #     ordering = ['headline']
    #     db_table = "Article"

    # def __str__(self):
    #     return self.headline

class Pet(models.Model):
    TYPE_CHOICES = (
        ('cat', 'Cat'),
        ('dog', 'Dog')
    )
    id = models.CharField('Mã Thú Cưng', max_length=10, primary_key=True)
    name = models.CharField('Tên Thú Cưng', max_length=30)
    age = models.IntegerField('Tuổi')
    type = models.CharField('Loại', max_length=3, choices=TYPE_CHOICES)
    weight = models.IntegerField('Cân Nặng')
    length = models.IntegerField('Chiều Dài')
    color = models.CharField('Màu Sắc', max_length=7) # #00FF1A
    vacinated = models.BooleanField()
    dewormed = models.BooleanField()
    sterilized = models.BooleanField()

    class Meta:
        db_table = "Pet"
        # ordering = ['-id']

myapp/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
from .models import Pet
# ModelForm: Form được tạo từ Model -> tạo ra những ô input y chang định nghĩa của model.
# Form: Dạng freestyle/custom form.
class PetForm(forms.ModelForm):
    class Meta:
        model = Pet # Form này dành cho Model nào
        fields = '__all__' # ('name', 'age', 'type') # Chọn ô input cho cột trong table đc hiển thị
        widgets = { # Thêm các thuộc tính HTML vào các ô input của form
            'id': forms.TextInput(attrs={'class': 'form-control'}),
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'age': forms.NumberInput(attrs={'class': 'form-control'}),
            'type': forms.Select(attrs={'class': 'form-control'}),
            'weight': forms.NumberInput(attrs={'class': 'form-control'}),
            'length': forms.NumberInput(attrs={'class': 'form-control'}),
            'color': forms.TextInput(attrs={'type': 'color', 'class': 'form-control'}),
            'vacinated': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
            'dewormed': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
            'sterilized': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        }

    def __init__(self,*args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.instance.pk:
            self.fields.pop('id', None)
            # self.fields.pop('name', None)

    # Khi tạo server validate thì tạo ở phia forms.
    # Khi muốn validate cho 1 field thì tạo hàm có dạng clean_<tên field muốn validate>

    # Pet không được trùng tên, id
    def clean_id(self):
        print("Validate Id")
        # Thử lấy Pet với id người dùng gửi lên.
        # Nếu trả về 1 pet object thì id đã trùng, báo lỗi
        # Nếu không trả về thì id chưa trùng, trả lại id tiếp tục xử lý
        try:
            pet_id = self.cleaned_data['id']
            Pet.objects.get(id=pet_id)
            print("Đã trùng id, văng lỗi")
            raise ValidationError(f'Pet với id={pet_id} đã tồn tại. Vui lòng nhập id khác')
        except Pet.DoesNotExist:
            print("Pet với id chưa tồn tại")
            return self.cleaned_data['id']

    def clean_name(self):
        if self.instance.id and self.instance.name == self.cleaned_data['name']:
            # Dành cho trường hợp edit Pet nhưng không sữa `name`
            return self.cleaned_data['name']
        print("Validate Name")
        # Thử lấy Pet với name người dùng gửi lên.
        # Nếu trả về 1 pet object thì name đã trùng, báo lỗi
        # Nếu không trả về thì name chưa trùng, trả lại name tiếp tục xử lý
        try:
            pet_name = self.cleaned_data['name']
            Pet.objects.get(name=pet_name)
            print("Đã trùng name, văng lỗi")
            raise ValidationError(f'Pet với name={pet_name} đã tồn tại. Vui lòng nhập name khác')
        except Pet.DoesNotExist:
            print("Pet với name chưa tồn tại")
            return self.cleaned_data['name']
# Form đăng ký RegistrationFrom
# Bắt buộc người dùng phải điền: 
    #username: username không trùng
    #password: 
    #first_name
    #last_name
    #email: email cũng không được

class RegistrationForm(forms.Form):
    username = forms.CharField(
        label="Tên Đăng Nhập",
        max_length=20,
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    password = forms.CharField(
        label="Mật Khẩu",
        max_length=20,
        widget=forms.PasswordInput(attrs={'class': 'form-control'})
    )
    confirm_password = forms.CharField(
        label="Nhập Lại Mật Khẩu",
        max_length=20,
        widget=forms.PasswordInput(attrs={'class': 'form-control'})
    )
    first_name = forms.CharField(
        label="Tên",
        max_length=20,
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    last_name = forms.CharField(
        label="Họ",
        max_length=20,
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    email = forms.CharField(
        label="Email",
        max_length=20,
        widget=forms.EmailInput(attrs={'class': 'form-control'})
    )

    # Kiễm tra username/email không trùng. password và confirm_password phải giống nhau
    def clean_username(self):
        username = self.cleaned_data['username']
        try:
            User.objects.get(username=username)
            raise ValidationError(f'Tên đăng nhập đã trùng')
        except User.DoesNotExist:
            return username

    def clean_email(self):
        email = self.cleaned_data['email']
        try:
            User.objects.get(email=email)
            raise ValidationError(f'Email đã trùng')
        except User.DoesNotExist:
            return email

    def clean_confirm_password(self):
        if self.cleaned_data['password'] != self.cleaned_data['confirm_password']:
            raise ValidationError("Mật khẩu và nhập lại không giống nhau")
        return self.cleaned_data['confirm_password']

    def save(self):
        User.objects.create_user( # create_user là lưu vào CSDL có hash password. create lưu dạng raw data
            username=self.cleaned_data['username'],
            password=self.cleaned_data['password'],
            first_name=self.cleaned_data['first_name'],
            last_name=self.cleaned_data['last_name'],
            email=self.cleaned_data['email'],
        )

class LoginForm(forms.Form):
    username = forms.CharField(
        label="Tên Đăng Nhập",
        max_length=20,
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    password = forms.CharField(
        label="Mật Khẩu",
        max_length=20,
        widget=forms.PasswordInput(attrs={'class': 'form-control'})
    )
    # # hàm này dùng để kiểm tra thông tin người dùng gửi lên
    # # Láy username, password check thông tin
    # def clean_password(self):
    #     username = self.cleaned_data['username']
    #     password = self.cleaned_data['password']
    #     try:
    #         # Thử get User từ username và password
    #         # Nếu trả về thì thông tin hợp lệ.

myapp/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from myapp.models import Student, Pet
from myapp.forms import PetForm
# Create your views here.
# View đầu tiên
# File views.py đóng vai trò là chữ C trong MVC.
# R: Read
def index(request):
    pets = Pet.objects.all()
    search = request.GET.get('search')
    if search:
        pets = Pet.objects.filter(name__icontains=search)
    paginator = Paginator(object_list=pets, per_page=5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    message = "Không có Pet" if len(pets) == 0 else ""
    return render(
        request=request,
        template_name='pet/index.html',
        context={
            'pets': pets,
            'message': message,
            'page_obj': page_obj
        }
    )

# C: CREATE
# Người phải đăng nhập thì mới add đc pet
@login_required(login_url='/user/login')
def add_pet(request):
    logged_user = request.user
    print(logged_user.has_perm('myapp.add_pet'))
    form = PetForm()
    if request.method == "POST":
        # Validation form
        # Server validation
        # form.save() # Giống model save()
        form = PetForm(request.POST)
        # return redirect('index')
        if form.is_valid(): # server validate có sẳn
            # print("Validate OK")
            form.save() # Giống model save()
            return redirect('index')
        # else:
        #     print("Lỗi")
        #     print(form.errors)
     
    return render(
        request=request,
        template_name='pet/add.html',
        context={
            'form': form
        }
    )

# U: UPDATE
@login_required(login_url='/user/login')
def update_pet(request, pet_id):
    pet = Pet.objects.get(id=pet_id)
    form = PetForm(instance=pet)
    if request.method == "POST":
        form = PetForm(request.POST, instance=pet)
        # print(request.POST)
        # form.save()
        # return redirect('index')
        if form.is_valid():
            form.save()
            return redirect('index')
        # else:
        #     print("Lỗi")
        #     print(form.errors)
    return render(
        request=request,
        template_name='pet/update.html',
        context={
            'form': form,
            'pet_id': pet_id
        }
    )

#V: Views
@login_required(login_url='/user/login')
def detail_pet(request, pet_id):
    pet = Pet.objects.get(id=pet_id)
    form = PetForm(instance=pet)
    return render(
        request=request,
        template_name='pet/detail.html',
        context={
            'form': form
        }
    )

# D: DELETE
@login_required(login_url='/user/login')
def delete_pet(request, pet_id):
    pet = Pet.objects.get(id=pet_id)
    pet.delete()
    return redirect('index')

# def students(request):
#     students = Student.objects.all()
#     # response = HttpResponse()
#     # response.write("<h1>Danh sách các Student trong database</h1>")
#     # response.write("<ol>")
#     # for student in students:
#     #     response.write(f"<li>Name: {student.name}, Age: {student.age} </li>")
#     # response.write("</ol>")
#     return render(
#         request=request,
#         template_name='students.html',
#         context={
#             'students': students # key <tên biến sẽ dùng bên HTML>: value <value là giá trị biến bên python truyền vào>
#         }#Biến được truyền từ views sang template HTML.
#     )

# def add_student(request):
#     if request.method == "POST":
#         Student.objects.create(
#             name=request.POST['name'],
#             age=int(request.POST['age']),
#             gender=request.POST['gender']=="True",
#             email=request.POST['email'],
#             phone=request.POST['phone']
#         )
#         return redirect('students')
#         # return HttpResponseRedirect('/myapp/students')
#     return render(
#         request=request, 
#         template_name='add_student.html'
#     )
# # 2 cách
# # Function base view - class base view
# def my_view(request): # Hàm trong views.py sẽ luôn có 1 tham số phải có
#     # request: HTTP Request
#     # respone = HttpResponse()
#     # respone.write("<h1>Hello các bạn lớp PYTHON2204</h1>")
#     # respone.write("<p style='color:blue'>Đây là nội dung của my view</p>")
#     # Phải trả về là HTTP Response
#     # 65535
#     # <1024 là hệ thống.
#     if request.method == "POST":
#         request.session['username'] = request.POST['name-username']
#     return render(request, 'myview.html')

# # Thứ tự các bạn dùng để tạo 1 view mới trong Django
# # Bước 1: Tạo hàm trong `view.py`
# def welcome(request):
#     response = HttpResponse()
#     response.write(f"Welcome {request.session['username']}")
#     return response

myapp/templates/pet/add.html
{% extends 'base/base.html' %}
{% block title %}
    Functions add pet | {{ block.super }}
{% endblock title %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-6 offset-3">
                <form action="" method="post">
                    {% csrf_token %}
                    {% for field in form %}
                        {% if field.field.widget.input_type == 'checkbox' %}
                            <div class="form-group form-check">
                                {{ field }}
                                {{ field.label }}
                        {% else %}
                            <div class="form-group {% if field.errors %}is-invalid{% else %}is-valid{% endif%}">
                                {{ field.label }}
                                {{ field }}
                        {% endif %}
                            {% if field.errors %}
                                {% for error in field.errors %}
                                    <div style="display: block" class="invalid-feedback">
                                        {{error}}
                                    </div>
                                {% endfor %}
                            {% endif %}
                        </div>
                    {% endfor %}
                    <input type="submit" value="Add">
                </form>
            </div>
        </div>
    </div>
{% endblock content %}
   

myapp/templates/pet/detail.html
{% extends 'base/base.html' %}

{% block title %}
    Functions detail view | {{ block.super }}
{% endblock title %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <table>
                    {{ form.as_table }}
                </table>
            </div>
        </div>
    </div>
{% endblock content %}

myapp/templates/pet/index.html
{% extends 'base/base.html' %}
{% block title %}
    Functions index views | {{ block.super }}
{% endblock title %}

{% block content %}
    {% load static %}
    {% load myfilter %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">ID</th>
                            <th scope="col">Name</th>
                            <th scope="col">Age</th>
                            <th scope="col">Type</th>
                            <th scope="col">Weight</th>
                            <th scope="col">Length</th>
                            <th scope="col">Color</th>
                            <th scope="col">Vacinated</th>
                            <th scope="col">Dewormed</th>
                            <th scope="col">Sterilized</th>
                            <th scope="col"><a href="{% url 'myapp:add_pet' %}">
                                    <i class="bi bi-plus-circle"></i>
                                </a></th> <!-- {  % url 'giá trị name trong urls.py '%   } -->
                        </tr>
                    </thead>
                    <tbody>
                        {% if message %}
                        <tr>
                            <td scopt="row" colspan="12">{{message}}</td>
                        </tr>
                        {% endif %}
                        {% for pet in page_obj %}
                        {% url 'myapp:detail_pet' pet_id=pet.id  as url_detail %}
                        {% url 'myapp:update_pet' pet_id=pet.id  as url_update %}
                        {% url 'myapp:delete_pet' pet_id=pet.id  as url_delete %}
                        {% include 'common/pet-item.html' with url_view=url_detail url_update=url_update url_delete=url_delete %}
                        {% endfor %}
                    </tbody>

                </table>
                {% include 'common/paginator.html'  with class_name='paginator-function' %}
            </div>
        </div>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="modalDeteltePet" tabindex="-1" aria-labelledby="modalDeteltePetLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="modalDeteltePetLabel">Modal title</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>Pet ID: <span id="pet_id"></span></p>
                    <p>Pet Name: <span id="pet_name"></span></p>
                    <p>Pet type: <span id="pet_type"></span></p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <a id="url-delete" class="btn btn-primary">OK</a>
                </div>
            </div>
        </div>
    </div>

    <script src="{% static 'js/jquery-3.6.0.slim.min.js' %}"></script>
    <script>
        $(".delete-pet").each(function () {
            $(this).click(function () {
                $("#pet_id").text($(this).parent().parent().children().eq(0).text());
                $("#pet_name").text($(this).parent().parent().children().eq(1).text());
                $("#pet_type").text($(this).parent().parent().children().eq(3).text());
                $("#url-delete").attr("href", $(this).data('url'));
                $("#modalDeteltePet").modal('show');
            })
        })
        function confirmDeletePet(event, petId) {
            if (confirm("Bạn có thực sự muốn xóa Pet với id là " + petId + " không ?") == true) {
                window.location.href = event.getAttribute('data-url');
            }
            else {
                console.log("Không xóa");
            }
        }
    </script>
{% endblock content %}

myapp/templates/pet/update.html
{% extends 'base/base.html' %}

{% block title %}
    Functions update view | {{ block.super}}
{% endblock title %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-6 offset-3">
                <form action="" method="post">
                    {% csrf_token %}
                    <div class="form-group is-valid">
                        Mã Thú Cưng
                        <input disabled type="text"class="form-control" value="{{pet_id}}">
                </div>
                    {% for field in form %}
                        {% if field.field.widget.input_type == 'checkbox' %}
                            <div class="form-group form-check">
                                {{ field }}
                                {{ field.label }}
                            
                        {% else %}
                            <div class="form-group {% if field.errors %}is-invalid{% else %}is-valid{% endif%}">
                                {{ field.label }}
                                {{ field }}
                            
                        {% endif %}
                            {% if field.errors %}
                                {% for error in field.errors %}
                                    <div style="display: block" class="invalid-feedback">
                                        {{error}}
                                    </div>
                                {% endfor %}
                            {% endif %}
                        </div>
                    {% endfor %}
                    <input type="submit" value="Update">
                </form>
            </div>
        </div>
    </div>
{% endblock content %}
        